### ISSUE TITLE
Most of my contacts never receive notifications (both Google Play and F-Droid)

### ISSUE THREAD

**Issue by bennypr0fane** [vector-im/riot-android#2800]
I've basically come to expect that a new contact will never be notified of messages from me! I know of two contacts that are reliably notified, for the others it's unreliable or never, unless the client is actually running.
People have come to the conclusion that Riot is just not working.

**Comment by BillCarsonFr** [comment]
Hi @bennypr0fane ,

Thanks for reaching out on these issues. We are currently investigating on some reported notifications issues, improvement will be released in the next version.
Meanwhile it would be helpful to have more information on your friends' devices (make & model, etc..).
Do you think you can ask them to send a bug report from the settings or by shaking the device, it will allow me to have access to more technical info and some logs.

Thanks.

**Comment by bennypr0fane** [comment]
In any case, how do I make sure you are notified of the reports I submit - and they're related to this issue?

**Comment by bennypr0fane** [comment]
A number of problem reports have been submitted.
If Riot/Matrix is supposed to be better at messaging than any e-mail service (currently, it's worse), these notification problems should be P1 since the beginning. Until this is fixed, people are better off using e-mail. An IM client (or protocol) that won't notify you of new messages basically defeats its own purpose.

**Comment by Flexmaen** [comment]
Similar problem here.
Most of the contacts I have in Riot suddenly stop the conversation. After I notify them somewhere else (when it was silent for about a week), they usually say "Oh sorry, I didn't get any notification from Riot and did overlook the message."

That not just happened once, it happens regularly with different contacts. I guess it happens when people don't use Riot too often. For some reason it seems to stop and only will be back again when you start it - something they never do if they think they didn't get any message anyway.

**Comment by neVERberleRfellerER** [comment]
Could this be extent of https://github.com/vector-im/riot-android/issues/2720 ? My contacts also reported just "I didn't get any notifications", but I asked them about last message they received and then we foud that some of them were not receiving messages at all. After client restart it works until aforementioned bug kick in again.

**Comment by bennypr0fane** [comment]
How can I tell whether or not my messages were sent in the first place?

**Comment by neVERberleRfellerER** [comment]
Well, I think you can trust it to error out loudly if sending failed (some screenshots in #2720 show this). However, you won't know if it was delivered if recipient uses only android client. Quite reliable method is to ask recipient through some other channel.

**Comment by bennypr0fane** [comment]
Well in that case, this issue is not related to #2720 (of course if messages were never sent, then there won't be a notification). This is about messages that do not appear as unsent on the sender's device, so that they would believe it was delivered, but the recipient is never notified.

**Comment by neVERberleRfellerER** [comment]
#2720 is quite big and affect both sending and receiving (the original reporter probably doesn't know; see my post https://github.com/vector-im/riot-android/issues/2720#issuecomment-471179321 - these all happen at once) and could affect both sides, but does ot have to. What happens is, that I send message to somebody, it is actually sent (e.g. I can see it in desktop clien), but due to #2720 (or ine of its extents) recipients never get the message on their android devices until they restart their client. The problem is, you don't know, the only way is to ask the recipient.

**Comment by Flexmaen** [comment]
> How can I tell whether or not my messages were sent in the first place?

I use Riot on my phone and on my computer. So when I sent the message on one device and have it on the conversation in the other device, I can be pretty sure that it was sent.
However like I said, there is still the problem that people often do not get any notification.

**Comment by neVERberleRfellerER** [comment]
@Flexmaen Can you confirm that recipients can see the message in their Android clients without restart (that you see it as sent does not mean that they actually received it to particular client)? Because I can't when somebody sends me a message, the same thing happens in reverse direction. This could tell if #1172 (and #2720) and this could happen independently (my testing shows that they can't, but maybe I was just lucky with notifications?)

**Comment by bennypr0fane** [comment]
@Flexmaen: Is it basically possible for a message to be delivered, i. e. the client receives it, but does not give a notification?
Here's how I would understand it roughly and schematically what happens:
- 1. The message is sent.
- 2. The server receives it.
- 3. It should do something to notify the client.
- 4. If that succeeds, the receiving user sees/hears the notification.
- 5. S/he opens the client, which then retrieves the message from the server

If this is some sort of correct, then what I suspect is not working properly here is 3.

**Comment by zwieberl** [comment]
Many of my contacts suffer from the same problem. 
I am hosting my own homeserver and those contacts are part of that. 
@bennypr0fane: Are you using your own homeserver or matrix.org?
Would be interesting to find out, if this affects all users or only self-hosted homeservers.

**Comment by bennypr0fane** [comment]
All of them are registered at matrix.org, except one, which is at disroot.org (also a public server).
I suspect it is a fault in the Matrix protocol and affects a large part of its users, I've heard numerous similar reports.

**Comment by Flexmaen** [comment]
I guess the solution might be simple:
People who had this problem reported that they didn't get any messages after they restarted their phone.  So, I just restarted my phone and reproduced the issue.

Seems that all we need is that Riot will be started automatically in that case.

**Comment by zwieberl** [comment]
I'm pretty sure my contacts are not always restarting their phones.
This might also be an issue, but most likely not the only one.

**Comment by Flexmaen** [comment]
I confirmed the issue with the restart on two phones (Android 8.1 and Android 7), while someone in the channel reported that he doesn't have the problem.
Also the friend who told me about this issue does not seem to have it always (Android 9).

So there seems to be a problem after restarts, but not always or for everyone.
Maybe it related to the Android version? Or to the used location/language settings?

@zwieberl In which time period do you have the problem that others don't respond anymore? For me this is not happening daily or weekly, but it happens after 1 or 2 months, which is a time period where people might restart their phone.

**Comment by bennypr0fane** [comment]
I would submit that most people restart their phones way more often then every month, but I can't prove that. Also can't reproduce the restart issue, if launching and closing Riot manually after a restart still, notifications still fail to come through - meaning a possible failure to launch Riot syncing after a restart would be a separate issue
1) reboot phone
2) launch Riot manually to exclude that as the possible reason for notifications not coming through
3) completely close Riot (not just to brackground).
4) Send message.
5) Still no notification.
@Flexmaen,  you should open a separate issue for the restart problem.

**Comment by zwieberl** [comment]
@Flexmaen That is really hard to tell, since I don't have that problem myself and seldom use it as an instant messaging, but more like email, so delays are very hard for me to interpret. 
I just get sometimes complains from my users, that "riot is not giving me notifications at all". They are non-technical people and I have no idea how often they do or don't get notifications. Some might not get any notifications but don't say anything and just periodically look into riot, while others might overstate the problem and only have the phone-restart problem you mentioned.

But I want to note that at least one of them is not Android but iOS.

But as @bennypr0fane said, I too believe that the phone-restart-bug is worth a separate issue.

**Comment by Flexmaen** [comment]
With the current version (0.9.00 G-ff636030f) it got worse.
Even when the phone wasn't restarted I had the problem that Riot for Android just ignored a call.
I also noticed that Riot is not available in the developer option "background check". I think older versions were.

**Comment by bennypr0fane** [comment]
> With the current version (0.9.00 G-ff636030f) it got worse.
> Even when the phone wasn't restarted I had the problem that Riot for Android just ignored a call (until I launched it manually).
I already said that it's not related to (or dependent on) restarts - this issue has from the beginning been that notifications are not received even without restarting the phone, so that also means it hasn't gotten worse, it just wasn't fixed.
Please stop bringing up restarts here and post it in a separate issue.

**Comment by Flexmaen** [comment]
Errm... I just mentioned that I did not restart the phone to make clear that don't mix the issues in this case.

**Comment by Thatoo** [comment]
I also know 4 people who have problem with notifications...

**Comment by BillCarsonFr** [comment]
Hi Thatoo, can we have more informations? 
I am considering closing existing reports on notification, as it as been re-worked; We will start clean by opening new issues

**Comment by Thatoo** [comment]
If I can help but I don't live with these person so I need to know what precise questions I should ask them. So far they just complain they don't get notifications, no ring or no led to warn them they received a message

**Comment by BillCarsonFr** [comment]
If they could just report a bug in app (shacking or via left drawer). Will allow at least to get device make/model , app version. and hopefully somethign in the logs

**Comment by bennypr0fane** [comment]
What exactly has been done based on previous bug reports? Any info regarding the specific nature of these re-workings?

**Comment by Flexmaen** [comment]
Btw, I noticed that some users who complained about missing notifications used the version of the F-Droid Store.
This version is outdated (0.8.28a, while 0.9.1 is on Play Store), and it also uses its own sync function instead of Google Push as far as I understand.

However, @bennypr0fane mentioned that this problem also happens for his contacts who got Riot from the Play Store, so should we open another issue for the F-Droid version?

**Comment by takiainen** [comment]
I havea friend using iOS who hasn't received notification for well over a year. We've been just waiting for it to be fixed. Then after the hacking incident I don't get notification either unless I specifically open the app to see if someone has written something. It is a serious issue an renders the app near useless.

**Comment by ekim501** [comment]
I have the Play Store version with a home server and have the same issue.  No one in my family receives notifications when a message comes in.  I sometimes can feel my phone vibrate so I know my phone received the message - but I don't hear any sounds so I miss most of them.

**Comment by gerroon** [comment]
I am wondering if a working federation with the Synapse server is required for message delivery for Google Push stuff (Gplay version).

I personally do not have any issues with message deliveries to Fdroid versior or Google Play versions (I use Fdroid version). When a message is received I  get a notification in the tray bar with Fdroid version.

Myu users are Iphone,. Android 8 and Android 7

**Comment by takiainen** [comment]
I have set everything into "noisy", and so have my friends who use to F-Droid version. Still no notifications.

Strange this is, which nobody hasn't addressed yet,that this issue started after the hacking incidet in April. My notifications worked before.

**Comment by gerroon** [comment]
@takiainen can you also try cleaning cache etc and restart, do this inside Riot's preferences, there is a button for it.

**Comment by bennypr0fane** [comment]
This issue has been reported to me by many users way before the hacking incident.
I believe most OEMs do terrible things with their homegrown versions of Android, e. g. extra battery saving mechanisms that make it impossible to wake up the phone from a deeper sleep. It would be very interesting to know how well the Pixel phones are doing with Riot/Matrix and other models with close-to-vanilla Android.

**Comment by sylph1o** [comment]
> Also, I would argue that not getting a call is not the same as not being notified of a message, as Riot uses WebRTC for calls - but then again Matrix is also the signalling layer for calls, just like for messages.

My experience supports that: I am notified of messages but not of calls (unless Riot is currently open). Additionally, if I open Riot _after_ missing a call, I get the ringtone and call notification (no possibility to pick up, though).

Riot version 0.9.2-dev (F-093f1c77d) on LineageOS 15.1.

**Comment by takiainen** [comment]
@gerroon  Unfortunately cleaning cache nor restarting doesn't help.

@bennypr0fane I have rooted Oneplus One running 16.0 Lineage os with microg (no GAPPS). I have also tried excluding Riot from the battery optimization, but it doesn't help. 

Bugs me to read glorious Matrix 1.0 success stories from their blog (out of beta!) when the most basic functionality i.e. notifications is not working and nobody seems to care. As someone pointed here, the issue has been present for a long time.

**Comment by gerroon** [comment]
@takiainen 

Does web client or desktop clients get notifications?

**Comment by ekim501** [comment]
For me web and desktop clients do get notifications but the android app does not.

**Comment by gerroon** [comment]
@ekim501

And you are using Gplay or Fdroid?

**Comment by ekim501** [comment]
Gplay with a home server.

**Comment by bennypr0fane** [comment]
I think it might be a good idea for everyone who reports not getting notifications in this post to check if they are getting those missed notifs on desktop/web clients!
Ideally, edit your previous posts to give this information - that would help make sure that your problem concerns the android client specifically!

**Comment by takiainen** [comment]
No problems with Riot desktop. It's the android F-DROID version (and iOS version for my friend).

**Comment by gerroon** [comment]
IOS version has been the most stable and trouble free one for me 

Fdroid cant take calls if it is not open in the front.


Can you ask your friend to open Fdroid version and keep it open and see if it can take messages while it is in the foreground?

**Comment by takiainen** [comment]
Messages come normally if FDROID version is open in the foreground. Even calls most of the time work well if the app is in the foreground.

**Comment by pakman** [comment]
I am using the F-droid version of Riot.im on Sailfish OS (with Alien Dalvik at version 4.4), and I only receive notifications of incoming messages if I actually open the app. This problem is the reason that I only use matrix to communicate with one other person - I cannot possibly recommend it to more people until this issue is resolved. I have enabled the Alien Dalvik setting "Allow application background services to start on bootup" for Riot.im, and I get occasional notifications that Riot is synchronising, but nothing when messages arrive.

My correspondent runs the iOS version of Riot.im, and receives notifications of incoming messages reliably, however I have to check from time to time for messages to me. I have enabled e-mail notifications as a partial workaround, but as @bennypr0fane has said this means that Riot.im is no better than e-mail in this respect.

I use the matrix.org server, with additional identities for testing. Desktop notifications using the Riot.im web app (in the Brave browser) work.

**Comment by kingwap99** [comment]
if you are establishing your own homeserver.
I think the root cause of this issue is synapse [#5101](https://github.com/matrix-org/synapse/issues/5101) 
some error on pusher

**Comment by pakman** [comment]
> if you are establishing your own homeserver.
> I think the root cause of this issue is synapse [#5101](https://github.com/matrix-org/synapse/issues/5101)
> some error on pusher

It is pretty clear that this affects users of the matrix.org server. Is it possible to find out whether or not matrix.org is running a version of the code that still has this bug?

Also, with the adoption of matrix by the French government ([Matrix in the French State](https://fosdem.org/2019/schedule/event/matrix_french_state/)) I can't help wondering whether they have cracked the problem. Adoption would be pretty low if they haven't. The French government's fork of Riot for Android is here: https://github.com/dinsic-pim/tchap-android and has clearly diverged (890 commits ahead, 1119 commits behind, as I write this).

This issue may be relevant: https://github.com/dinsic-pim/tchap-android/issues/381 but appears to have been fixed. I wonder if there has been a regression in vector-im/riot-android?

**Comment by kingwap99** [comment]
try this [link](https://federationtester.matrix.org/) 
can show the version of a Homeserver

**Comment by bennypr0fane** [comment]
That gives:
`"Version": {
    "name": "Synapse",
    "version": "1.3.1 (b=matrix-org-hotfixes,9240622c1,dirty)"`
for me today.

**Comment by java-py-c-cpp-js** [comment]
Some person I know is using Riot and he had a lot of problems with notifications. We both using the F-Droid version. I could fix some error with turning the notification mode to "optimized for real time" so the notification is received every time I send some message. But one problem remains: After the smartphone is started, all notifications are without sound. If a received message is opened, it is working the every next messages until the next reboot of the smartphone. If Riot.im was opened before without opening a newly received message, this doesn't has the fixing effect so the following notifications are recieved without sound, too.

Version Riot.im: 0.9.8 F-Droid.
Smartphone: Cubot King Kong
Android: 7.0

My Smartphone - same settings, everything is working:
S5 with LineageOS 16/ Android 9
Same Riot.im version from F-Droid

I'm not very sure if this error fits in this issue or if I should create a new one.
